# Generated by Django 4.2.7 on 2023-11-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='garçon',
            options={'ordering': ('nome',), 'verbose_name_plural': 'Garçons'},
        ),
        migrations.AlterModelOptions(
            name='gerente',
            options={'ordering': ('nome',), 'verbose_name_plural': 'Gerentes'},
        ),
        migrations.AddField(
            model_name='garçon',
            name='nm_casa',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='gerente',
            name='nm_casa',
            field=models.IntegerField(default=20),
        ),
    ]
