# Generated by Django 4.2.7 on 2023-11-29 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0006_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
