# Generated by Django 4.2.7 on 2023-12-01 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bd', '0007_delete_customuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Garçon',
            new_name='Garçom',
        ),
    ]
